### ISSUE TITLE
Assignment of Tasks and Team Information for Ruby group capstone

### ISSUE THREAD

**Issue by DevaWinner** [Dorcas126/Ruby-Group-capstone#31]
Hello,

We have set up our Kanban Board and below are the details:

- **GitHub Project Link**: https://github.com/Dorcas126/Ruby-Group-capstone/projects/1
  
- **Team Size**: We have 3 team members.

- **Assignment of Tasks**:

    - Team member 1: @Dorcas126 
      - Assigned tasks listed for Team member 1
    
    - Team member 2: @DevaWinner 
      - Assigned tasks listed for Team member 2

    - Team member 3: @ClarenceAtim 
      - Assigned tasks listed for Team member 3

We split the group task equally.

Please review and approve accordingly. Thank you!

**Comment by julie-ify** [comment]
Hi @DevaWinner, @Dorcas126 and @ClarenceAtim,

## Highlights!
- Descriptive tasks and issue ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
